<#
.SYNOPSIS
    Retrieve alerts generated by Microsoft Defender for Endpoint.

.DESCRIPTION
    This script uses Microsoft Graph API to retrieve a list of security alerts generated by Microsoft Defender for Endpoint.

.PARAMETER AppId
    The Application (client) ID of the Azure AD app.

.PARAMETER TenantId
    The Directory (tenant) ID.

.PARAMETER CertThumbprint
    The certificate thumbprint for authentication.

.EXAMPLE
    .\Get-DefenderAlerts.ps1 -AppId "YourAppId" -TenantId "YourTenantId" -CertThumbprint "YourCertThumbprint"

#>
param (
    [Parameter(Mandatory = $true)]
    [string]$AppId,

    [Parameter(Mandatory = $true)]
    [string]$TenantId,

    [Parameter(Mandatory = $true)]
    [string]$CertThumbprint
)

Connect-MgGraph -AppId $AppId -TenantId $TenantId -CertificateThumbprint $CertThumbprint -Scopes "SecurityEvents.Read.All" -NoWelcome

# Example using client secret (uncomment to use):
# Connect-MgGraph -ClientId $AppId -TenantId $TenantId -ClientSecret "YourClientSecret" -Scopes "SecurityEvents.Read.All" -NoWelcome

Write-Host "Retrieving alerts..."
$alerts = Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/security/alerts" -Method GET

$alerts | Format-Table id, title, severity, status, createdDateTime

Disconnect-MgGraph
